export const coddleTheme = {
  colors: {
    background: '#FFF9F2',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    primary: '#FF4F8B',
    primarySoft: '#FFE3EE',
    primaryDark: '#E6396B',
    accentYellow: '#FFD86B',
    accentMint: '#8DD7A5',
    accentPurple: '#B9A5FF',
    accentBlue: '#8FD5FF',
    accentPeach: '#FFB79C',
    textPrimary: '#333544',
    textSecondary: '#777A8C',
    textTertiary: '#A0A3B8',
    textOnPrimary: '#FFFFFF',
    success: '#8DD7A5',
    warning: '#FFD86B',
    error: '#FF5C5C',
    info: '#8FD5FF',
    border: '#E5E5F0',
    divider: '#F0F0F5',
    shadow: 'rgba(0, 0, 0, 0.05)',
    sleepNight: '#8FD5FF',
    sleepNap: '#B9A5FF',
    sleepActive: '#FF4F8B',
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    pill: 999,
    round: 9999,
  },
  spacing: (multiplier: number) => 4 * multiplier,
};


